### ISSUE TITLE
ProMcUtilities Updates - 5-7-21

### ISSUE THREAD

**Issue by goflishMC** [promcteam/promcutilities#7]
- Change name to PROMCUTILITIES
- change the authors to Travja, goflish
- fix the lore stuff that's saving in that strange way
- Set "removeOnDeath" to true by default
- Set "dropOnDeath" to true by default
- Make sure, canDrop and tradeable are set to true by default
- Raname economy base command to /pmcu
- Raname base permission nodes to pmcu
- update on github

**Comment by Travja** [comment]
Everything but fixing lore is done!

**Comment by Travja** [comment]
Lore is fixed with modifications to RiseCore
